"""Generate firmware execution defaults from the same physical profile data as host.

Run with --check in CI. This never connects to a controller.
"""
import argparse
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'host'))
from playback.hardware_profiles import HardwareRegistry


def generate():
    registry = HardwareRegistry()
    lines = ['// Generated by scripts/generate_hardware_profiles.py; edit JSON profiles, not this file.',
             '#pragma once', '#include <stdint.h>', 'namespace orchestra { namespace physical {']
    for key, value in registry.protocol.items():
        lines.append(f'constexpr uint32_t {key} = {value}u;')
    for family, profile in [('fdd','FDD'), ('sled','DVD_SLED')]:
        ps = [registry.effective(profile,f'{family}:{i}') for i in range(1,5)]
        if family=='fdd':
            fields=[('fddTravel','travelSteps',lambda p:p.get('travelSteps')),
                    ('fddReversalUs','reversalIntervalMs',lambda p:round(p.get('reversalIntervalMs')*1000)),
                    ('fddMinStepUs','executionMinStepUs',lambda p:p.get('executionMinStepUs') or round(p.get('datasheetMinStepMs')*1000))]
        else:
            fields=[('sledTravel','travelSteps',lambda p:p.get('travelSteps') if p.get('travelSteps') is not None else -1),
                    ('sledAcceleration','accelerationLimit',lambda p:p.get('accelerationLimit')),
                    ('sledPitchRatio','pitchRatio',lambda p:p.get('pitchRatio'))]
        for variable,_,value in fields:
            ctype='float' if variable in ('sledAcceleration','sledPitchRatio') else 'int32_t'
            values=', '.join(str(value(p)) + ('f' if ctype=='float' else '') for p in ps)
            # float literals must contain a decimal point in C++.
            if ctype=='float': values=', '.join(f'{float(value(p))}f' for p in ps)
            lines.append(f'constexpr {ctype} {variable}[4] = {{{values}}};')
    ps = [registry.effective('DVD_SLED', f'sled:{i}') for i in range(1, 5)]
    bands = [p.get('allowedBandsHz') or [] for p in ps]
    width = max(1, max(map(len, bands)))
    lines.append('constexpr uint8_t sledAllowedBandCount[4] = {' + ', '.join(str(len(b)) for b in bands) + '};')
    entries = []
    for group in bands:
        entries.append('{' + ', '.join('{%sf, %sf}' % (float(a), float(b)) for a, b in group + [[0, 0]] * (width - len(group))) + '}')
    lines.append(f'constexpr float sledAllowedBandsHz[4][{width}][2] = ' + '{' + ', '.join(entries) + '};')
    lines.extend([
        'inline bool sledFrequencyAllowed(uint8_t id, float stepHz) {',
        ' if (!sledAllowedBandCount[id]) return true;',
        ' for (uint8_t i=0; i<sledAllowedBandCount[id]; ++i)',
        '  if (stepHz>=sledAllowedBandsHz[id][i][0] && stepHz<=sledAllowedBandsHz[id][i][1]) return true;',
        ' return false;', '}',
    ])
    ps=[registry.effective('HDD_PERCUSSION',f'hdd:{i}') for i in range(1,5)]
    for key in ('parkMs','settleMs','strikeMs'):
        values=', '.join(str(round(p.get(key)*1000))+'u' for p in ps)
        lines.append(f"constexpr uint32_t hdd{key[0].upper()+key[1:-2]}Us[4] = {{{values}}};")
    lines.append('}}')
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    target=ROOT/'firmware/controller/include/hardware_profiles_generated.h'
    content=generate()
    if args.check:
        if not target.exists() or target.read_text()!=content: raise SystemExit('execution defaults out of date')
    else: target.write_text(content)
