[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>

[env:esp32]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<esp32/main.cpp>
